# Generated by Django 4.1.3 on 2022-11-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Furniture', max_length=30)),
                ('item_stock', models.IntegerField(null=True)),
            ],
        ),
    ]
