# Generated by Django 4.1.3 on 2022-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='name',
            field=models.CharField(default='Furniture', max_length=30, unique=True),
        ),
    ]
